name: Selenium tests

on:
  issue_comment:
    types: [created]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest
    name: Selenium tests
    steps:
      - run: |
          echo "${{github.event.comment}}"
